# Generated by Django 3.2.16 on 2022-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='img',
            field=models.ImageField(upload_to='pics1'),
        ),
    ]
